plugins: fetchart embedart lastgenre inline discogs missing bandcamp copyartifacts
directory: D:/Music/Sorted
library: D:/Music/Data/musiclibrary.db
art_filename: cover
threaded: yes
original_date: no
per_disc_numbering: yes
clutter:
- Thumbs.DB
- .DS_Store

extrafiles:
    patterns:
        all: '*.*'

copyartifacts:
    extensions: .cue .log .*


missing:
    format: $albumartist - $album - $title
    count: no
    total: no

item_fields:
    advdisctitle: u" - %s" % (disctitle) if len(disctitle) > 1 else u""
    disc_and_track: u"%02i - %02i" % (disc, track) if
                    disctotal > 1 else "%02i" % (track)
    multidisc: 1 if disctotal > 1 else 0

album_fields:
    adv_disc: |
        u" %dxCD" % (disctotal) if disctotal > 1 else u""
    advyear: |
        years = 0
        release_years = 0
        for item in items:
            years += item.original_year
            release_years += item.year
        if years == 0 and release_years == 0:
            return u"0000"
        elif years == 0:
            return u"%i"%(items[0].year)
        else:
            return u"%i"%(items[0].original_year)
    advrelease: |
        years = 0
        infos = []
        for item in items:
            years += item.original_year
        if years == 0 or items[0].year == items[0].original_year:
            pass
        else:
            infos.append("%i"%(items[0].year))
        if label != "":
            infos.append(label)
        if catalognum != "":
            infos.append(catalognum)
        final_infos = " (" + ", ".join(infos) + ")"
        if len(infos) == 0:
            final_infos = ""
        return final_infos

    advformat: |
        total = 0
        format = items[0].format
        for item in items:
            total += item.bitrate
        abr = total / len(items) / 1000 
        if format != "MP3":
            return u"%s"%(format)
        else:
            ## based on LAME presets https://trac.ffmpeg.org/wiki/Encode/MP3
            if abr in [8, 16, 24, 32, 40, 48, 64, 80, 96, 112, 128, 160, 192, 224, 256, 320]:
                return u"MP3 %dk"%(abr)
            elif abr >= 245:
                return u"MP3 V0"
            elif abr >= 225:
                return u"MP3 V1"
            elif abr >= 190:
                return u"MP3 V2"
            elif abr >= 175:
                return u"MP3 V3"
            elif abr >= 165:
                return u"MP3 V4"
            elif abr >= 130:
                return u"MP3 V5"
            elif abr >= 115:
                return u"MP3 V6"
            elif abr >= 100:
                return u"MP3 V7"
            elif abr >= 85:
                return u"MP3 V8"
            elif abr >= 65:
                return u"MP3 V9"
            else:
                return u"MP3 %dk"%(abr)


paths:
    default: $albumartist/$advyear - $album%aunique{} [$advformat]$adv_disc/%if{$multidisc,Disc $disc$advdisctitle/}$disc_and_track - $title
    singleton: $artist/Single Tracks/$artist - $title
    comp: _Compilations/$album%aunique{} ($advyear) [$advformat]$adv_disc/%if{$multidisc,Disc $disc$advdisctitle/}$disc_and_track - $title
    albumtype_soundtrack: _Soundtracks/$album%aunique{} ($advyear) [$advformat]$adv_disc/%if{$multidisc,Disc $disc$advdisctitle/}$disc_and_track - $title

import:
    write: yes
    bell: yes
    copy: yes
    move: no
    resume: ask
    incremental: no
    quiet_fallback: skip
    timid: yes
    log: D:/Music/Data/beet.log

match:
    strong_rec_thresh: 0.05
